before_install:
  - sudo apt-get -y -qq install curl make libgc-dev libglew1.6-dev libglu-dev libftgl-dev
  - git clone --depth=1 git://github.com/nddrylliog/rock.git 
  - (cd rock && make -s quick-rescue)
  - export PATH=$PATH:$PWD/rock/bin
  - mkdir dummyprefix
  - export PREFIX=$PWD/dummyprefix
  - export PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig
  - export PATH=$PATH:$PWD/rock/bin:$PWD/dummyprefix/bin
  - wget http://libsdl.org/release/SDL2-2.0.1.tar.gz -O - | tar xz
  - (cd SDL2-2.0.1 && ./configure --prefix=$PREFIX && make -j5 && make install)
  - git clone --depth=1 git://github.com/geckojsc/ooc-sdl2.git
  - git clone --depth=1 git://github.com/nddrylliog/ooc-glew.git
  - git clone --depth=1 git://github.com/nddrylliog/ooc-glu.git

script:
  - export OOC_LIBS=$PWD
  - cd samples
  - mkdir -p travis
  - rock -v sdl-ftgl.ooc -o=travis/sdl-ftgl


